services:
  - type: web
    name: ai-course-whatsapp-chatbot
    env: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_AD_ACCOUNT_ID
        sync: false
